### ISSUE TITLE
Is there a way to import this module to have it available in all imported files?

### ISSUE THREAD

**Issue by Kreyren** [kirelagin/dns.nix#19]
Currently i have to put this codeblock in all imported files to have `dns.*` available:

```nix
# https://git.dotya.ml/RiXotStudio/system-management/src/commit/bb1a8104567c95c3502dab31a5854010d7441d7f/services/named/bind.nix#L4
dns = import (pkgs.fetchFromGitHub {
	owner = "kirelagin";
	repo = "dns.nix";
	rev = "v1.1.0";
	sha256 = "0zvg92fjrfmdylk8ic3b2srsrqc8ii94a1ir0v5sknjyxvy5f3rf";
});
```

Is there a way to define this as a module to have it available in all imported files to avoid duplicate code e.g.

```nix
{ config, lib, dns, ... }:
	let
		zoneFile = dns.util.${builtins.currentSystem}.writeZone "${config.networking.fqdn}" (import (../../domains + "/${config.networking.domain}" + /machines + "/${config.networking.hostName}" + /zones/main.nix) { inherit dns; inherit config; });
	in {
		networking.firewall.allowedTCPPorts = lib.optional config.services.bind.enable 53;

		services.bind = {
			# FIXME(Krey): Research as tor's DNS is only resolving A and AAAA ?
			# forwarders = if(config.services.tor.client.dns.enable == true )
			# 	then [
			# 		# BUG(Krey): https://github.com/NixOS/nixpkgs/issues/129714
			# 		"127.0.0.1 port 9053"
			# 	]
			# 	else [ ];
			zones = {
				"${config.networking.fqdn}" = {
					file = zoneFile;
					master = true;
					masters = [ "${config.networking.interfaces.enp7s0.ipv4.addresses}" ];
				};
			};
		};
	}
```

Notice the `{ config, lib, dns, ... }:`

### Context

I am trying to solve this for 4 days while none in matrix channel for nixOS knows how to do this without causing an infinite recursion as highlighted in https://github.com/NixOS/nix/issues/5007

**Comment by kirelagin** [comment]
This is how I do this using flakes:

1. [Use `specialArgs` to pass all flake inputs to modules](https://github.com/kirelagin/infra/blob/a601151ba32d06fe28f4252ec39697d714db39ce/flake.nix#L27)
2. [Receive flake inputs in a module](https://github.com/kirelagin/infra/blob/a601151ba32d06fe28f4252ec39697d714db39ce/modules/apps/dns/elagin.me.nix#L5)
3. [Use the `dns` flake input](https://github.com/kirelagin/infra/blob/a601151ba32d06fe28f4252ec39697d714db39ce/modules/apps/dns/elagin.me.nix#L8)

Off the top of my head, I am not exactly sure how to do this without flakes, since you are probably not calling `nixpkgs.lib.nixosSystem` yourself, but I bet there is a way to pass `dns` as an special arg to all modules, similar how to `lib` or `pkgs` is passed.

**Comment by kirelagin** [comment]
If I am reading the code of `evalModules` correcly, all you need to do is set:

```nix
{

  _module.args = {
    dns = import ...
  };

in your system configuration and `dns` will be automatically passed to all modules.

See also:

* https://stackoverflow.com/a/47713963/603094
* https://discourse.nixos.org/t/variables-for-a-system/2342
* https://discourse.nixos.org/t/why-do-i-not-have-to-pass-input-parameters-to-certain-nixos-modules/13057

**Comment by Kreyren** [comment]
that works!

THANK YOUUU!!!
